version: '3.8'

services:
  big-data-health-api:
    container_name: big-data-health-api
    # entrypoint: sh -c 'pnpm install --frozen-lockfile && pnpm run start:dev'
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - big-data-health
  

  postgres:
    container_name: big-data-health-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: big_data_health_db
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql
    networks:
      - big-data-health

networks:
  big-data-health:

volumes:
  db: